# Generated by Django 5.2.8 on 2025-11-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('EM_USO', 'Em uso'), ('ESTOQUE', 'Estoque'), ('MANUTENCAO', 'Manutenção')], default='EM_USO', max_length=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
